package com.su.JobTracker.mapper;

import com.su.JobTracker.model.company;
import com.su.JobTracker.model.companyExample;
import com.su.JobTracker.response.CompanyResponse;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface companyMapper {
	
	int insertCompany(company row);

	int deleteCompany(int company_id);
	
	List<CompanyResponse> findCompanyByName(String company_name, Integer offset, Integer limit);
	
	company findCompanyByNameAndUserId(String company_name, int user_id);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    long countByExample(companyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByExample(companyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insert(company row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insertSelective(company row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    List<company> selectByExample(companyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    company selectByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExampleSelective(@Param("row") company row, @Param("example") companyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExample(@Param("row") company row, @Param("example") companyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKeySelective(company row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKey(company row);
}