package com.su.JobTracker.mapper;

import com.su.JobTracker.model.savedJob;
import com.su.JobTracker.model.savedJobExample;
import com.su.JobTracker.response.SavedJobResponse;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface savedJobMapper {
	int deleteSavedJobByPostingId(int user_id, int job_posting_id);
	List<SavedJobResponse> findUnexpiredSavedJobByUserId(int user_id, Date now);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saved_jobs
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    long countByExample(savedJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saved_jobs
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByExample(savedJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saved_jobs
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByPrimaryKey(Integer savedJobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saved_jobs
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insert(savedJob row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saved_jobs
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insertSelective(savedJob row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saved_jobs
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    List<savedJob> selectByExample(savedJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saved_jobs
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    savedJob selectByPrimaryKey(Integer savedJobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saved_jobs
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExampleSelective(@Param("row") savedJob row, @Param("example") savedJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saved_jobs
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExample(@Param("row") savedJob row, @Param("example") savedJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saved_jobs
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKeySelective(savedJob row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saved_jobs
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKey(savedJob row);
}