package com.su.JobTracker.mapper;

import com.su.JobTracker.model.userCompany;
import com.su.JobTracker.model.userCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface userCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    long countByExample(userCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByExample(userCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByPrimaryKey(Integer userCompanyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insert(userCompany row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insertSelective(userCompany row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    List<userCompany> selectByExample(userCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    userCompany selectByPrimaryKey(Integer userCompanyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExampleSelective(@Param("row") userCompany row, @Param("example") userCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExample(@Param("row") userCompany row, @Param("example") userCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKeySelective(userCompany row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_companies
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKey(userCompany row);
}