package com.su.JobTracker.response;

import java.util.Date;

public class ReviewResponse {

	private Integer reviewId;

	private Integer companyId;

	private Integer userId;

	private Integer rating;

	private String title;

	private Date reviewDate;


	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column reviews.review_id
	 *
	 * @return the value of reviews.review_id
	 *
	 * @mbg.generated Sat Nov 02 23:25:48 CST 2024
	 */
	public Integer getReviewId() {
		return reviewId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column reviews.review_id
	 *
	 * @param reviewId the value for reviews.review_id
	 *
	 * @mbg.generated Sat Nov 02 23:25:48 CST 2024
	 */
	public void setReviewId(Integer reviewId) {
		this.reviewId = reviewId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column reviews.company_id
	 *
	 * @return the value of reviews.company_id
	 *
	 * @mbg.generated Sat Nov 02 23:25:48 CST 2024
	 */
	public Integer getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column reviews.company_id
	 *
	 * @param companyId the value for reviews.company_id
	 *
	 * @mbg.generated Sat Nov 02 23:25:48 CST 2024
	 */
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column reviews.user_id
	 *
	 * @return the value of reviews.user_id
	 *
	 * @mbg.generated Sat Nov 02 23:25:48 CST 2024
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column reviews.user_id
	 *
	 * @param userId the value for reviews.user_id
	 *
	 * @mbg.generated Sat Nov 02 23:25:48 CST 2024
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column reviews.rating
	 *
	 * @return the value of reviews.rating
	 *
	 * @mbg.generated Sat Nov 02 23:25:48 CST 2024
	 */
	public Integer getRating() {
		return rating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column reviews.rating
	 *
	 * @param rating the value for reviews.rating
	 *
	 * @mbg.generated Sat Nov 02 23:25:48 CST 2024
	 */
	public void setRating(Integer rating) {
		this.rating = rating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column reviews.title
	 *
	 * @return the value of reviews.title
	 *
	 * @mbg.generated Sat Nov 02 23:25:48 CST 2024
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column reviews.title
	 *
	 * @param title the value for reviews.title
	 *
	 * @mbg.generated Sat Nov 02 23:25:48 CST 2024
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column reviews.review_date
	 *
	 * @return the value of reviews.review_date
	 *
	 * @mbg.generated Sat Nov 02 23:25:48 CST 2024
	 */
	public Date getReviewDate() {
		return reviewDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column reviews.review_date
	 *
	 * @param reviewDate the value for reviews.review_date
	 *
	 * @mbg.generated Sat Nov 02 23:25:48 CST 2024
	 */
	public void setReviewDate(Date reviewDate) {
		this.reviewDate = reviewDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column reviews.content
	 *
	 * @return the value of reviews.content
	 *
	 * @mbg.generated Sat Nov 02 23:25:48 CST 2024
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column reviews.content
	 *
	 * @param content the value for reviews.content
	 *
	 * @mbg.generated Sat Nov 02 23:25:48 CST 2024
	 */
	public void setContent(String content) {
		this.content = content;
	}
}
