package com.su.JobTracker.mapper;

import com.su.JobTracker.model.applicationStatusHistory;
import com.su.JobTracker.model.applicationStatusHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface applicationStatusHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_status_history
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    long countByExample(applicationStatusHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_status_history
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByExample(applicationStatusHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_status_history
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByPrimaryKey(Integer statusHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_status_history
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insert(applicationStatusHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_status_history
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insertSelective(applicationStatusHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_status_history
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    List<applicationStatusHistory> selectByExample(applicationStatusHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_status_history
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    applicationStatusHistory selectByPrimaryKey(Integer statusHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_status_history
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExampleSelective(@Param("row") applicationStatusHistory row, @Param("example") applicationStatusHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_status_history
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExample(@Param("row") applicationStatusHistory row, @Param("example") applicationStatusHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_status_history
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKeySelective(applicationStatusHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_status_history
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKey(applicationStatusHistory row);
}