package com.su.JobTracker.mapper;

import com.su.JobTracker.model.jobApplication;
import com.su.JobTracker.model.jobApplicationExample;
import com.su.JobTracker.response.JobApplicationResponse;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface jobApplicationMapper {
	JobApplicationResponse findDetailedJobApplicationById(int application_id);
	
	List<JobApplicationResponse> findDetailedJobApplicationByUserId(@Param("user_id")int user_id,@Param("limit") int limit,@Param("offset") int offset,@Param("isInProgress")  int isInProgress);
	
	List<JobApplicationResponse> findDetailedJobApplicationByCompanyId(@Param("company_id")int company_id,@Param("limit") int limit,@Param("offset") int offset,@Param("isInProgress")  int isInProgress);
	
	List<JobApplicationResponse> findDetailedJobApplicationByJobPostingId(@Param("job_posting_id") int job_posting_id, @Param("limit") int limit, @Param("offset") int offset, @Param("isInProgress") int isInProgress);
	
	int countInProgressByCompanyId(int company_id, int isInProgress);
	
	int countInProgressByUserId(int user_id, int isInProgress);
	
	int countInProgressByJobPostingId(int job_posting_id, int isInProgress);
	
	int countByCompanyId(int company_id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_applications
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    long countByExample(jobApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_applications
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByExample(jobApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_applications
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByPrimaryKey(Integer applicationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_applications
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insert(jobApplication row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_applications
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insertSelective(jobApplication row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_applications
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    List<jobApplication> selectByExampleWithBLOBs(jobApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_applications
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    List<jobApplication> selectByExample(jobApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_applications
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    jobApplication selectByPrimaryKey(Integer applicationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_applications
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExampleSelective(@Param("row") jobApplication row, @Param("example") jobApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_applications
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("row") jobApplication row, @Param("example") jobApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_applications
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExample(@Param("row") jobApplication row, @Param("example") jobApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_applications
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKeySelective(jobApplication row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_applications
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(jobApplication row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_applications
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKey(jobApplication row);
}