package com.su.JobTracker.mapper;

import com.su.JobTracker.model.jobPosting;
import com.su.JobTracker.model.jobPostingExample;
import com.su.JobTracker.model.jobPostingWithBLOBs;
import com.su.JobTracker.param.JobSearchParams;
import com.su.JobTracker.response.JobSearchResponse;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface jobPostingMapper {
	List<JobSearchResponse> findUnexpiredJobPosting(@Param("params") JobSearchParams params, @Param("limit") int limit, @Param("offset") int offset);
	
	List<JobSearchResponse> findJobPostingByCompanyId(int company_id, int limit, int offset);
	
	List<JobSearchResponse> findUnexpiredJobPostingByCompanyId(int company_id, Date now, int limit, int offset);
	
	List<JobSearchResponse> findExpiredJobPostingByCompanyId(int company_id, Date now, int limit, int offset);
	
	JobSearchResponse findJobPostingByPostingId(int job_posting_id);
	
	int countUnexpiredJobPosting(@Param("params") JobSearchParams params);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    long countByExample(jobPostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByExample(jobPostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByPrimaryKey(Integer jobPostingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insert(jobPostingWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insertSelective(jobPostingWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    List<jobPostingWithBLOBs> selectByExampleWithBLOBs(jobPostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    List<jobPosting> selectByExample(jobPostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    jobPostingWithBLOBs selectByPrimaryKey(Integer jobPostingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExampleSelective(@Param("row") jobPostingWithBLOBs row, @Param("example") jobPostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("row") jobPostingWithBLOBs row, @Param("example") jobPostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExample(@Param("row") jobPosting row, @Param("example") jobPostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKeySelective(jobPostingWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(jobPostingWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKey(jobPosting row);
}