package com.su.JobTracker.mapper;

import com.su.JobTracker.model.review;
import com.su.JobTracker.model.reviewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface reviewMapper {
	List<com.su.JobTracker.response.ReviewResponse> findReviewByUserId(int user_id, int offset, int limit, int order);
	
	List<com.su.JobTracker.response.ReviewResponse> findReviewByCompanyId(int company_id, int offset, int limit, int order);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    long countByExample(reviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByExample(reviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByPrimaryKey(Integer reviewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insert(review row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insertSelective(review row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    List<review> selectByExampleWithBLOBs(reviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    List<review> selectByExample(reviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    review selectByPrimaryKey(Integer reviewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExampleSelective(@Param("row") review row, @Param("example") reviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("row") review row, @Param("example") reviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExample(@Param("row") review row, @Param("example") reviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKeySelective(review row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(review row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKey(review row);
}