package com.su.JobTracker.mapper;

import com.su.JobTracker.model.user;
import com.su.JobTracker.model.userExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface userMapper {
	/**
	 * 
	 * @param userId User's ID
	 * @return 
	 */
	int disableUser(Integer userId);
	/**
	 * 
	 * @param userId  User's ID
	 * @param newPassword User's new password
	 * @return
	 */
	int updatePassword(@Param("userId")Integer userId, @Param("newPassword")String newPassword);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registered_users
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    long countByExample(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registered_users
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByExample(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registered_users
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registered_users
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insert(user row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registered_users
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int insertSelective(user row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registered_users
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    List<user> selectByExample(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registered_users
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    user selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registered_users
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExampleSelective(@Param("row") user row, @Param("example") userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registered_users
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByExample(@Param("row") user row, @Param("example") userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registered_users
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKeySelective(user row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registered_users
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    int updateByPrimaryKey(user row);
}