package com.su.JobTracker.model;

import java.util.Date;

public class applicationStatusHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_status_history.status_history_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer statusHistoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_status_history.application_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer applicationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_status_history.status
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_status_history.changed_by
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer changedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_status_history.change_date
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Date changeDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_status_history.status_history_id
     *
     * @return the value of application_status_history.status_history_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getStatusHistoryId() {
        return statusHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_status_history.status_history_id
     *
     * @param statusHistoryId the value for application_status_history.status_history_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setStatusHistoryId(Integer statusHistoryId) {
        this.statusHistoryId = statusHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_status_history.application_id
     *
     * @return the value of application_status_history.application_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_status_history.application_id
     *
     * @param applicationId the value for application_status_history.application_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_status_history.status
     *
     * @return the value of application_status_history.status
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_status_history.status
     *
     * @param status the value for application_status_history.status
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_status_history.changed_by
     *
     * @return the value of application_status_history.changed_by
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getChangedBy() {
        return changedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_status_history.changed_by
     *
     * @param changedBy the value for application_status_history.changed_by
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setChangedBy(Integer changedBy) {
        this.changedBy = changedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_status_history.change_date
     *
     * @return the value of application_status_history.change_date
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Date getChangeDate() {
        return changeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_status_history.change_date
     *
     * @param changeDate the value for application_status_history.change_date
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setChangeDate(Date changeDate) {
        this.changeDate = changeDate;
    }
}