package com.su.JobTracker.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class jobPostingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public jobPostingExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andJobPostingIdIsNull() {
            addCriterion("job_posting_id is null");
            return (Criteria) this;
        }

        public Criteria andJobPostingIdIsNotNull() {
            addCriterion("job_posting_id is not null");
            return (Criteria) this;
        }

        public Criteria andJobPostingIdEqualTo(Integer value) {
            addCriterion("job_posting_id =", value, "jobPostingId");
            return (Criteria) this;
        }

        public Criteria andJobPostingIdNotEqualTo(Integer value) {
            addCriterion("job_posting_id <>", value, "jobPostingId");
            return (Criteria) this;
        }

        public Criteria andJobPostingIdGreaterThan(Integer value) {
            addCriterion("job_posting_id >", value, "jobPostingId");
            return (Criteria) this;
        }

        public Criteria andJobPostingIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("job_posting_id >=", value, "jobPostingId");
            return (Criteria) this;
        }

        public Criteria andJobPostingIdLessThan(Integer value) {
            addCriterion("job_posting_id <", value, "jobPostingId");
            return (Criteria) this;
        }

        public Criteria andJobPostingIdLessThanOrEqualTo(Integer value) {
            addCriterion("job_posting_id <=", value, "jobPostingId");
            return (Criteria) this;
        }

        public Criteria andJobPostingIdIn(List<Integer> values) {
            addCriterion("job_posting_id in", values, "jobPostingId");
            return (Criteria) this;
        }

        public Criteria andJobPostingIdNotIn(List<Integer> values) {
            addCriterion("job_posting_id not in", values, "jobPostingId");
            return (Criteria) this;
        }

        public Criteria andJobPostingIdBetween(Integer value1, Integer value2) {
            addCriterion("job_posting_id between", value1, value2, "jobPostingId");
            return (Criteria) this;
        }

        public Criteria andJobPostingIdNotBetween(Integer value1, Integer value2) {
            addCriterion("job_posting_id not between", value1, value2, "jobPostingId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Integer value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Integer value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Integer value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Integer value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Integer> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Integer> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("location like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeIsNull() {
            addCriterion("employment_type is null");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeIsNotNull() {
            addCriterion("employment_type is not null");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeEqualTo(String value) {
            addCriterion("employment_type =", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeNotEqualTo(String value) {
            addCriterion("employment_type <>", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeGreaterThan(String value) {
            addCriterion("employment_type >", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeGreaterThanOrEqualTo(String value) {
            addCriterion("employment_type >=", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeLessThan(String value) {
            addCriterion("employment_type <", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeLessThanOrEqualTo(String value) {
            addCriterion("employment_type <=", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeLike(String value) {
            addCriterion("employment_type like", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeNotLike(String value) {
            addCriterion("employment_type not like", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeIn(List<String> values) {
            addCriterion("employment_type in", values, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeNotIn(List<String> values) {
            addCriterion("employment_type not in", values, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeBetween(String value1, String value2) {
            addCriterion("employment_type between", value1, value2, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeNotBetween(String value1, String value2) {
            addCriterion("employment_type not between", value1, value2, "employmentType");
            return (Criteria) this;
        }

        public Criteria andSalaryRangeIsNull() {
            addCriterion("salary_range is null");
            return (Criteria) this;
        }

        public Criteria andSalaryRangeIsNotNull() {
            addCriterion("salary_range is not null");
            return (Criteria) this;
        }

        public Criteria andSalaryRangeEqualTo(String value) {
            addCriterion("salary_range =", value, "salaryRange");
            return (Criteria) this;
        }

        public Criteria andSalaryRangeNotEqualTo(String value) {
            addCriterion("salary_range <>", value, "salaryRange");
            return (Criteria) this;
        }

        public Criteria andSalaryRangeGreaterThan(String value) {
            addCriterion("salary_range >", value, "salaryRange");
            return (Criteria) this;
        }

        public Criteria andSalaryRangeGreaterThanOrEqualTo(String value) {
            addCriterion("salary_range >=", value, "salaryRange");
            return (Criteria) this;
        }

        public Criteria andSalaryRangeLessThan(String value) {
            addCriterion("salary_range <", value, "salaryRange");
            return (Criteria) this;
        }

        public Criteria andSalaryRangeLessThanOrEqualTo(String value) {
            addCriterion("salary_range <=", value, "salaryRange");
            return (Criteria) this;
        }

        public Criteria andSalaryRangeLike(String value) {
            addCriterion("salary_range like", value, "salaryRange");
            return (Criteria) this;
        }

        public Criteria andSalaryRangeNotLike(String value) {
            addCriterion("salary_range not like", value, "salaryRange");
            return (Criteria) this;
        }

        public Criteria andSalaryRangeIn(List<String> values) {
            addCriterion("salary_range in", values, "salaryRange");
            return (Criteria) this;
        }

        public Criteria andSalaryRangeNotIn(List<String> values) {
            addCriterion("salary_range not in", values, "salaryRange");
            return (Criteria) this;
        }

        public Criteria andSalaryRangeBetween(String value1, String value2) {
            addCriterion("salary_range between", value1, value2, "salaryRange");
            return (Criteria) this;
        }

        public Criteria andSalaryRangeNotBetween(String value1, String value2) {
            addCriterion("salary_range not between", value1, value2, "salaryRange");
            return (Criteria) this;
        }

        public Criteria andPostedDateIsNull() {
            addCriterion("posted_date is null");
            return (Criteria) this;
        }

        public Criteria andPostedDateIsNotNull() {
            addCriterion("posted_date is not null");
            return (Criteria) this;
        }

        public Criteria andPostedDateEqualTo(Date value) {
            addCriterionForJDBCDate("posted_date =", value, "postedDate");
            return (Criteria) this;
        }

        public Criteria andPostedDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("posted_date <>", value, "postedDate");
            return (Criteria) this;
        }

        public Criteria andPostedDateGreaterThan(Date value) {
            addCriterionForJDBCDate("posted_date >", value, "postedDate");
            return (Criteria) this;
        }

        public Criteria andPostedDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("posted_date >=", value, "postedDate");
            return (Criteria) this;
        }

        public Criteria andPostedDateLessThan(Date value) {
            addCriterionForJDBCDate("posted_date <", value, "postedDate");
            return (Criteria) this;
        }

        public Criteria andPostedDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("posted_date <=", value, "postedDate");
            return (Criteria) this;
        }

        public Criteria andPostedDateIn(List<Date> values) {
            addCriterionForJDBCDate("posted_date in", values, "postedDate");
            return (Criteria) this;
        }

        public Criteria andPostedDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("posted_date not in", values, "postedDate");
            return (Criteria) this;
        }

        public Criteria andPostedDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("posted_date between", value1, value2, "postedDate");
            return (Criteria) this;
        }

        public Criteria andPostedDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("posted_date not between", value1, value2, "postedDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateIsNull() {
            addCriterion("closing_date is null");
            return (Criteria) this;
        }

        public Criteria andClosingDateIsNotNull() {
            addCriterion("closing_date is not null");
            return (Criteria) this;
        }

        public Criteria andClosingDateEqualTo(Date value) {
            addCriterionForJDBCDate("closing_date =", value, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("closing_date <>", value, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateGreaterThan(Date value) {
            addCriterionForJDBCDate("closing_date >", value, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("closing_date >=", value, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateLessThan(Date value) {
            addCriterionForJDBCDate("closing_date <", value, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("closing_date <=", value, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateIn(List<Date> values) {
            addCriterionForJDBCDate("closing_date in", values, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("closing_date not in", values, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("closing_date between", value1, value2, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("closing_date not between", value1, value2, "closingDate");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job_postings
     *
     * @mbg.generated do_not_delete_during_merge Sat Nov 02 23:25:48 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job_postings
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}