package com.su.JobTracker.model;

import java.util.Date;

public class jobPosting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_postings.job_posting_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer jobPostingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_postings.company_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_postings.title
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_postings.location
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_postings.employment_type
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String employmentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_postings.salary_range
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String salaryRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_postings.posted_date
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Date postedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_postings.closing_date
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Date closingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_postings.created_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_postings.updated_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_postings.job_posting_id
     *
     * @return the value of job_postings.job_posting_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getJobPostingId() {
        return jobPostingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_postings.job_posting_id
     *
     * @param jobPostingId the value for job_postings.job_posting_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setJobPostingId(Integer jobPostingId) {
        this.jobPostingId = jobPostingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_postings.company_id
     *
     * @return the value of job_postings.company_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_postings.company_id
     *
     * @param companyId the value for job_postings.company_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_postings.title
     *
     * @return the value of job_postings.title
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_postings.title
     *
     * @param title the value for job_postings.title
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_postings.location
     *
     * @return the value of job_postings.location
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_postings.location
     *
     * @param location the value for job_postings.location
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_postings.employment_type
     *
     * @return the value of job_postings.employment_type
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getEmploymentType() {
        return employmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_postings.employment_type
     *
     * @param employmentType the value for job_postings.employment_type
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setEmploymentType(String employmentType) {
        this.employmentType = employmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_postings.salary_range
     *
     * @return the value of job_postings.salary_range
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getSalaryRange() {
        return salaryRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_postings.salary_range
     *
     * @param salaryRange the value for job_postings.salary_range
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setSalaryRange(String salaryRange) {
        this.salaryRange = salaryRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_postings.posted_date
     *
     * @return the value of job_postings.posted_date
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Date getPostedDate() {
        return postedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_postings.posted_date
     *
     * @param postedDate the value for job_postings.posted_date
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setPostedDate(Date postedDate) {
        this.postedDate = postedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_postings.closing_date
     *
     * @return the value of job_postings.closing_date
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Date getClosingDate() {
        return closingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_postings.closing_date
     *
     * @param closingDate the value for job_postings.closing_date
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setClosingDate(Date closingDate) {
        this.closingDate = closingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_postings.created_at
     *
     * @return the value of job_postings.created_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_postings.created_at
     *
     * @param createdAt the value for job_postings.created_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_postings.updated_at
     *
     * @return the value of job_postings.updated_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_postings.updated_at
     *
     * @param updatedAt the value for job_postings.updated_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}