package com.su.JobTracker.model;

import java.util.Date;

public class message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.message_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.sender_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer senderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.receiver_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.timestamp
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.read_status
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Boolean readStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.content
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.message_id
     *
     * @return the value of messages.message_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.message_id
     *
     * @param messageId the value for messages.message_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.sender_id
     *
     * @return the value of messages.sender_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.sender_id
     *
     * @param senderId the value for messages.sender_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setSenderId(Integer senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.receiver_id
     *
     * @return the value of messages.receiver_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.receiver_id
     *
     * @param receiverId the value for messages.receiver_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.timestamp
     *
     * @return the value of messages.timestamp
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.timestamp
     *
     * @param timestamp the value for messages.timestamp
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.read_status
     *
     * @return the value of messages.read_status
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Boolean getReadStatus() {
        return readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.read_status
     *
     * @param readStatus the value for messages.read_status
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setReadStatus(Boolean readStatus) {
        this.readStatus = readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.content
     *
     * @return the value of messages.content
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.content
     *
     * @param content the value for messages.content
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setContent(String content) {
        this.content = content;
    }
}