package com.su.JobTracker.model;

public class userCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_companies.user_company_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer userCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_companies.user_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_companies.company_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_companies.position
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_companies.user_company_id
     *
     * @return the value of user_companies.user_company_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getUserCompanyId() {
        return userCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_companies.user_company_id
     *
     * @param userCompanyId the value for user_companies.user_company_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setUserCompanyId(Integer userCompanyId) {
        this.userCompanyId = userCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_companies.user_id
     *
     * @return the value of user_companies.user_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_companies.user_id
     *
     * @param userId the value for user_companies.user_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_companies.company_id
     *
     * @return the value of user_companies.company_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_companies.company_id
     *
     * @param companyId the value for user_companies.company_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_companies.position
     *
     * @return the value of user_companies.position
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_companies.position
     *
     * @param position the value for user_companies.position
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setPosition(String position) {
        this.position = position;
    }
}