package com.su.JobTracker.model;

import java.util.Date;

public class company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companies.company_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companies.company_name
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companies.location
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companies.industry
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companies.website
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companies.created_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companies.updated_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companies.company_id
     *
     * @return the value of companies.company_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companies.company_id
     *
     * @param companyId the value for companies.company_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companies.company_name
     *
     * @return the value of companies.company_name
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companies.company_name
     *
     * @param companyName the value for companies.company_name
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companies.location
     *
     * @return the value of companies.location
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companies.location
     *
     * @param location the value for companies.location
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companies.industry
     *
     * @return the value of companies.industry
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companies.industry
     *
     * @param industry the value for companies.industry
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setIndustry(String industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companies.website
     *
     * @return the value of companies.website
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companies.website
     *
     * @param website the value for companies.website
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companies.created_at
     *
     * @return the value of companies.created_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companies.created_at
     *
     * @param createdAt the value for companies.created_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companies.updated_at
     *
     * @return the value of companies.updated_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companies.updated_at
     *
     * @param updatedAt the value for companies.updated_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}