package com.su.JobTracker.model;

import java.util.Date;

public class jobApplication {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_applications.application_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer applicationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_applications.user_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_applications.job_posting_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer jobPostingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_applications.application_status
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String applicationStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_applications.application_date
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Date applicationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_applications.notes
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_applications.application_id
     *
     * @return the value of job_applications.application_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_applications.application_id
     *
     * @param applicationId the value for job_applications.application_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_applications.user_id
     *
     * @return the value of job_applications.user_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_applications.user_id
     *
     * @param userId the value for job_applications.user_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_applications.job_posting_id
     *
     * @return the value of job_applications.job_posting_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getJobPostingId() {
        return jobPostingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_applications.job_posting_id
     *
     * @param jobPostingId the value for job_applications.job_posting_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setJobPostingId(Integer jobPostingId) {
        this.jobPostingId = jobPostingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_applications.application_status
     *
     * @return the value of job_applications.application_status
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getApplicationStatus() {
        return applicationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_applications.application_status
     *
     * @param applicationStatus the value for job_applications.application_status
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setApplicationStatus(String applicationStatus) {
        this.applicationStatus = applicationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_applications.application_date
     *
     * @return the value of job_applications.application_date
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Date getApplicationDate() {
        return applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_applications.application_date
     *
     * @param applicationDate the value for job_applications.application_date
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setApplicationDate(Date applicationDate) {
        this.applicationDate = applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_applications.notes
     *
     * @return the value of job_applications.notes
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_applications.notes
     *
     * @param notes the value for job_applications.notes
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }
}