package com.su.JobTracker.model;

public class jobPostingWithBLOBs extends jobPosting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_postings.description
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_postings.requirements
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String requirements;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_postings.responsibilities
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private String responsibilities;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_postings.description
     *
     * @return the value of job_postings.description
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_postings.description
     *
     * @param description the value for job_postings.description
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_postings.requirements
     *
     * @return the value of job_postings.requirements
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getRequirements() {
        return requirements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_postings.requirements
     *
     * @param requirements the value for job_postings.requirements
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setRequirements(String requirements) {
        this.requirements = requirements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_postings.responsibilities
     *
     * @return the value of job_postings.responsibilities
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getResponsibilities() {
        return responsibilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_postings.responsibilities
     *
     * @param responsibilities the value for job_postings.responsibilities
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setResponsibilities(String responsibilities) {
        this.responsibilities = responsibilities;
    }
}