package com.su.JobTracker.model;

import java.util.Date;

public class savedJob {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saved_jobs.saved_job_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer savedJobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saved_jobs.user_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saved_jobs.job_posting_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Integer jobPostingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saved_jobs.saved_date
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Date savedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saved_jobs.saved_job_id
     *
     * @return the value of saved_jobs.saved_job_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getSavedJobId() {
        return savedJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saved_jobs.saved_job_id
     *
     * @param savedJobId the value for saved_jobs.saved_job_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setSavedJobId(Integer savedJobId) {
        this.savedJobId = savedJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saved_jobs.user_id
     *
     * @return the value of saved_jobs.user_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saved_jobs.user_id
     *
     * @param userId the value for saved_jobs.user_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saved_jobs.job_posting_id
     *
     * @return the value of saved_jobs.job_posting_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getJobPostingId() {
        return jobPostingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saved_jobs.job_posting_id
     *
     * @param jobPostingId the value for saved_jobs.job_posting_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setJobPostingId(Integer jobPostingId) {
        this.jobPostingId = jobPostingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saved_jobs.saved_date
     *
     * @return the value of saved_jobs.saved_date
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Date getSavedDate() {
        return savedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saved_jobs.saved_date
     *
     * @param savedDate the value for saved_jobs.saved_date
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setSavedDate(Date savedDate) {
        this.savedDate = savedDate;
    }
}