package com.su.JobTracker.model;

import java.util.Date;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;



public class user {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registered_users.user_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registered_users.name
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    @NotBlank(message = "Name cannot be null")
    @Size(min = 1, max = 50, message = "Name must be within 50 words")
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registered_users.email
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    @Email(message = "Email cannot be null")
    @Column(unique = true)
    @NotBlank(message = "Email must be a valid email address")
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registered_users.password
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    @NotBlank(message = "Password cannot be null")
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registered_users.role
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    @NotBlank(message = "Role cannot be null")
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registered_users.created_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registered_users.updated_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registered_users.user_id
     *
     * @return the value of registered_users.user_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registered_users.user_id
     *
     * @param userId the value for registered_users.user_id
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registered_users.name
     *
     * @return the value of registered_users.name
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registered_users.name
     *
     * @param name the value for registered_users.name
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registered_users.email
     *
     * @return the value of registered_users.email
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registered_users.email
     *
     * @param email the value for registered_users.email
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registered_users.password
     *
     * @return the value of registered_users.password
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registered_users.password
     *
     * @param password the value for registered_users.password
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registered_users.role
     *
     * @return the value of registered_users.role
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registered_users.role
     *
     * @param role the value for registered_users.role
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registered_users.created_at
     *
     * @return the value of registered_users.created_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registered_users.created_at
     *
     * @param createdAt the value for registered_users.created_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registered_users.updated_at
     *
     * @return the value of registered_users.updated_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registered_users.updated_at
     *
     * @param updatedAt the value for registered_users.updated_at
     *
     * @mbg.generated Sat Nov 02 23:25:48 CST 2024
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}